### ISSUE TITLE
Could you please upload the code of CCA used to map the image and their caption into a shared space?

### ISSUE THREAD

**Issue by xdhhh** [dot27/temporal-tessellation#1]

**Comment by GilLevi** [comment]
Thank you for your interest in our work.

The CCA code can be found in the following link, under hglmm_fv_v1.6.zip, taken from [1] : 
https://owncloud.cs.tau.ac.il/index.php/s/vb7ys8Xe8J8s8vo

[1] Klein, Benjamin, et al. "Associating neural word embeddings with deep image representations using fisher vectors." Proceedings of the IEEE Conference on Computer Vision and Pattern Recognition. 2015.‏

**Comment by llafcode** [comment]
Hi,
I'm also interested in your work, but the CCA code you provided seems not working now.
Could you please verify it?
Thank you very much.

**Comment by GilLevi** [comment]
Hi, I'm afraid we can't help in this as we are not the authors of that code.
